### ISSUE TITLE
specs falls

### ISSUE THREAD

**Issue by kompolom** [bem/bem-react-boilerplate#17]
first case:
```
 bem-react-boilerplate@0.1.0 test D:\learning\bem-in-react
> jest

 FAIL  src/blocks/App/App.test.tsx
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jest-runner/node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.658s, estimated 3s
Ran all test suites.
```
second case:
```
> bem-react-boilerplate@0.1.0 test D:\learning\bem-in-react
> jest

 FAIL  src/blocks/App/App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    D:\learning\bem-in-react\src\blocks\App\Logo\App-Logo.svg:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3">
                                                                                             ^

    SyntaxError: Unexpected token <

       6 | import './App-Header.css';
       7 | 
    >  8 | const logoSvg = require('../Logo/App-Logo.svg');
         |                 ^
       9 | 
      10 | export interface IElemProps {
      11 |   title: string;

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runner/node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/blocks/App/Header/App-Header.tsx:8:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.648s
Ran all test suites.
```

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/bem-react-boilerplate/pull/18
